Repository grafana/azure-data-explorer-datasource, pull requests merged in 2020-09, with the labels that each got.

#120 v3: fixing issues with dynamic columns and time filter.
  CHANGELOG.md
  package.json
  src/KustoExpressionParser.ts
  src/QueryEditor.tsx
  src/components/VisualQueryEditor.tsx
  src/datasource.ts
  src/schema/AdxAutoComplete.ts
Labels: bug

#129 Added has, !has and has_any in the where filter
  src/components/VisualQueryEditorSections.tsx
Labels: effort/small, enhancement

#130 Small fixes
  src/components/VisualQueryEditor.tsx
  src/components/VisualQueryEditorSections.tsx
  src/datasource.ts
  src/partials/config.html
  src/types.ts
Labels: enhancement

#132 DatasourceSettings: Adds default editor mode
  src/QueryEditor.tsx
  src/components/QueryEditorToolbar.tsx
  src/config_ctrl.ts
  src/datasource.test.ts
  src/datasource.ts
  src/partials/config.html
  src/types.ts
Labels: enhancement

#141 Refactoring of query parser and included all selected filter when doing the auto complete
  src/KustoExpressionParser.test.ts
  src/KustoExpressionParser.ts
  src/components/VisualQueryEditor.tsx
  src/datasource.ts
  src/editor/components/filter/QueryEditorFieldAndOperator.tsx
  src/editor/components/filter/QueryEditorFilterSection.tsx
  src/editor/components/groupBy/QueryEditorGroupBySection.tsx
  src/editor/components/reduce/QueryEditorReduceSection.tsx
  src/editor/components/types.ts
  src/schema/AdxAutoComplete.ts
  src/types.ts
Labels: enhancement

#143 Refactor: switches to use AsyncSelect instead of Select
  src/editor/components/field/QueryEditorField.test.tsx
  src/editor/components/field/QueryEditorField.tsx
Labels: enhancement

#150 Refactor: Makes Select full width
  src/editor/components/operators/QueryEditorOperator.tsx
Labels: enhancement

#146 Refactor: Fixes missing bind for autoCompleteQuery function
  src/datasource.ts
Labels: bug

#148 Refactor: Sorts autocomplete values that startsWith searched text first
  jest.config.js
  src/datasource.test.ts
  src/datasource.ts
Labels: enhancement

#147 Refactor: Fixes so backspace removes selected value
  src/editor/components/field/QueryEditorField.tsx
Labels: enhancement

#153 When changing time shift we should re-generate the query
  src/components/VisualQueryEditor.tsx
Labels: bug

#152 Excluding empty operators/where values from generated query
  src/KustoExpressionParser.test.ts
  src/KustoExpressionParser.ts
Labels: bug

#151 Display template variables on top of selector with columns/tables/databases
  src/editor/components/field/QueryEditorField.tsx
Labels: bug

#145 Autocomplete should populate some of the values prior to typing
  src/KustoExpressionParser.test.ts
  src/KustoExpressionParser.ts
  src/editor/components/filter/QueryEditorFieldAndOperator.tsx
  src/editor/components/operators/QueryEditorMultiOperator.tsx
  src/editor/components/operators/QueryEditorSingleOperator.tsx
Labels: enhancement

#154 Bugfix: time shift work as expectes
  src/KustoExpressionParser.test.ts
  src/KustoExpressionParser.ts
Labels: bug

#155 Bugfix: fixes during testing session
  src/KustoExpressionParser.test.ts
  src/KustoExpressionParser.ts
  src/components/VisualQueryEditorSections.tsx
  src/datasource.ts
  src/editor/components/operators/QueryEditorNumberOperator.tsx
  src/editor/components/operators/QueryEditorOperator.tsx
  src/editor/components/operators/QueryEditorStringOperator.tsx
  src/editor/guards.ts
Labels: bug
