Repository grafana/azure-data-explorer-datasource, pull requests merged in 2023-09, with the labels that each got.

#616 Add Docker image builds and post `docker pull` commands for local testing
  .github/workflows/pull-request-image.yml
Labels: datasource/ADX, type/chore

#617 Prepare 4.6.3 release
  CHANGELOG.md
  package.json
Labels: effort/none

#610 `ConfigEditor` updates
  .config/.eslintrc
  .config/Dockerfile
  .config/README.md
  .config/jest-setup.js
  .config/jest.config.js
  .config/jest/mocks/react-inlinesvg.tsx
  .config/jest/utils.js
  .config/tsconfig.json
  .config/webpack/utils.ts
  .config/webpack/webpack.config.ts
  .github/workflows/detect-breaking-changes.yml
  .nvmrc
  README.md
  cypress/integration/smoke.spec.ts
  package.json
  src/components/ConfigEditor/AzureCredentials.ts
  src/components/ConfigEditor/AzureCredentialsForm.tsx
  src/components/ConfigEditor/ConfigHelp.tsx
  src/components/ConfigEditor/ConnectionConfig.tsx
  src/components/ConfigEditor/DatabaseConfig.test.tsx
  src/components/ConfigEditor/DatabaseConfig.tsx
  src/components/ConfigEditor/Divider.tsx
  src/components/ConfigEditor/OpenAIConfig.tsx
  src/components/ConfigEditor/QueryConfig.tsx
  src/components/ConfigEditor/TrackingConfig.tsx
  src/components/ConfigEditor/index.tsx
  src/components/QueryEditor/index.tsx
  src/datasource.ts
  src/plugin.json
  src/test/selectors.ts
  src/tracking.ts
  yarn.lock
Labels: effort/small, type/chore

#622 Find and replace existing comment when creating a PR build
  .github/workflows/pull-request-image.yml
Labels: effort/small, datasource/ADX
