Repository grafana/azure-data-explorer-datasource, pull requests merged in 2024-02, with the labels that each got.

#757 OpenAI: Add explain button to KQL query
  src/components/QueryEditor/QueryHeader.test.tsx
  src/components/QueryEditor/QueryHeader.tsx
Labels: effort/small, datasource/ADX

#782 Prepare 4.10.0 release
  CHANGELOG.md
  package.json
Labels: effort/none

#791 Add group to dependabot.yml for @grafana dependencies
  .github/dependabot.yml
Labels: github_actions
