Repository grafana/azure-data-explorer-datasource, pull requests merged in 2024-03, with the labels that each got.

#815 Bypass trusted endpoint enforcement for cluster request
  pkg/azuredx/client/httpclient.go
Labels: type/bug, effort/small

#822 Use correct error message property
  pkg/azuredx/client/testdata/error-response.json
  pkg/azuredx/models/types.go
  pkg/azuredx/testdata/error-response.json
Labels: changelog

#827 Prepare 5.0.0
  CHANGELOG.md
  package.json
Labels: type/chore
