Repository grafana/azure-data-explorer-datasource, pull requests merged in 2024-08, with the labels that each got.

#972 Respect default editor mode
  src/components/QueryEditor/QueryEditor.tsx
Labels: changelog

#996 Add `errorsource`
  cspell.config.json
  pkg/azuredx/client/client.go
  pkg/azuredx/datasource.go
  pkg/azuredx/datasource_test.go
  pkg/azuredx/helpers/helpers.go
  src/components/QueryEditor/QueryEditor.tsx
Labels: effort/medium, type/chore

#1000 Prepare 5.0.6
  CHANGELOG.md
  package.json
Labels: type/chore

#1001 Fix bug where query row was not showing properly
  src/components/QueryEditor/QueryEditor.tsx
  src/components/QueryEditor/VisualQueryEditor/AggregateSection.tsx
  src/components/QueryEditor/VisualQueryEditor/FilterSection.tsx
  src/components/QueryEditor/VisualQueryEditor/GroupBySection.tsx
  src/components/QueryEditor/VisualQueryEditor/TableSection.tsx
Labels: effort/small, datasource/ADX
