Repository grafana/azure-data-explorer-datasource, pull requests merged in 2025-06, with the labels that each got.

#1301 Internationalisation: Add markup for translations
  .eslintrc
  .gitignore
  .prettierrc.js
  .yarn/releases/yarn-4.9.1.cjs
  .yarnrc.yml
  crowdin.yml
  cspell.config.json
  eslint.config.js
  package.json
  src/components/ConfigEditor/ApplicationConfig.tsx
  src/components/ConfigEditor/AzureCredentialsConfig.ts
  src/components/ConfigEditor/AzureCredentialsForm.tsx
  src/components/ConfigEditor/ConfigHelp.tsx
  src/components/ConfigEditor/ConnectionConfig.tsx
  src/components/ConfigEditor/DatabaseConfig.tsx
  src/components/ConfigEditor/QueryConfig.tsx
  src/components/ConfigEditor/TrackingConfig.tsx
  src/components/ConfigEditor/index.tsx
  src/components/QueryEditor/EditorHelp.tsx
  src/components/QueryEditor/OpenAIEditor.tsx
  src/components/QueryEditor/QueryEditor.tsx
  src/components/QueryEditor/QueryHeader.tsx
  src/components/QueryEditor/RawQueryEditor.tsx
  src/components/QueryEditor/Suggestions.ts
  src/components/QueryEditor/VisualQueryEditor.test.tsx
  src/components/QueryEditor/VisualQueryEditor.tsx
  src/components/QueryEditor/VisualQueryEditor/AggregateItem.test.tsx
  src/components/QueryEditor/VisualQueryEditor/AggregateItem.tsx
  src/components/QueryEditor/VisualQueryEditor/AggregateSection.test.tsx
  src/components/QueryEditor/VisualQueryEditor/AggregateSection.tsx
  src/components/QueryEditor/VisualQueryEditor/FilterItem.test.tsx
  src/components/QueryEditor/VisualQueryEditor/FilterItem.tsx
  src/components/QueryEditor/VisualQueryEditor/FilterSection.tsx
  src/components/QueryEditor/VisualQueryEditor/GroupByItem.test.tsx
  src/components/QueryEditor/VisualQueryEditor/GroupByItem.tsx
  src/components/QueryEditor/VisualQueryEditor/GroupBySection.test.tsx
  src/components/QueryEditor/VisualQueryEditor/GroupBySection.tsx
  src/components/QueryEditor/VisualQueryEditor/KQLFilter.test.tsx
  src/components/QueryEditor/VisualQueryEditor/KQLPreview.tsx
  src/components/QueryEditor/VisualQueryEditor/TableSection.tsx
  src/components/QueryEditor/VisualQueryEditor/Timeshift.test.tsx
  src/components/QueryEditor/VisualQueryEditor/Timeshift.tsx
  src/components/VariableEditor/VariableEditor.test.tsx
  src/components/VariableEditor/VariableEditor.tsx
  src/locales/en-US/grafana-azure-data-explorer-datasource.json
  src/locales/i18next-parser.config.cjs
  src/module.ts
  src/plugin.json
  webpack.config.ts
  yarn.lock
Labels: changelog

#1283 Improve OBO related error messages
  pkg/azuredx/adxauth/obo_token_provider.go
Labels: effort/small

#1291 Add support for comparison operators with `datetime` and `timespan` types
  src/KustoExpressionParser.test.ts
  src/KustoExpressionParser.ts
  src/components/QueryEditor/VisualQueryEditor/utils/utils.ts
Labels: effort/small, changelog
